import type { DefaultProperty, PluginCatalogItem } from './types';

/**
 * Built-in plugin catalog shown in the plugin installer.
 * These are well-known Minecraft plugins users can "install" from the panel.
 */
export const PLUGIN_CATALOG: PluginCatalogItem[] = [
  {
    name: 'EssentialsX',
    description: 'The essential plugin suite for Spigot-based servers: homes, warps, kits, and more.',
    version: '2.20.1',
    author: 'EssentialsX Team',
    category: 'Admin',
    downloads: '12.4M',
    icon: 'Wrench',
  },
  {
    name: 'LuckPerms',
    description: 'A permissions plugin with advanced group management and a powerful editor.',
    version: '5.4.108',
    author: 'Luck',
    category: 'Permissions',
    downloads: '9.8M',
    icon: 'ShieldCheck',
  },
  {
    name: 'WorldEdit',
    description: 'Powerful in-game map editor. Select, copy, paste, and manipulate regions.',
    version: '7.3.0',
    author: 'EngineHub',
    category: 'World',
    downloads: '15.1M',
    icon: 'Globe',
  },
  {
    name: 'Vault',
    description: 'Economy and permissions API bridge required by many other plugins.',
    version: '1.7.3',
    author: 'Sleaker',
    category: 'API',
    downloads: '8.2M',
    icon: 'Database',
  },
  {
    name: 'ProtocolLib',
    description: 'Hook into the Minecraft protocol for packet-level plugin development.',
    version: '5.3.0',
    author: 'dmulloy2',
    category: 'API',
    downloads: '6.7M',
    icon: 'Network',
  },
  {
    name: 'CoreProtect',
    description: 'Log and rollback block changes, grief detection, and player actions.',
    version: '22.4',
    author: 'Intelli',
    category: 'Anti-Grief',
    downloads: '4.1M',
    icon: 'History',
  },
  {
    name: 'PlaceholderAPI',
    description: 'Inject dynamic placeholders into any text that supports it.',
    version: '2.11.6',
    author: 'HelpChat',
    category: 'API',
    downloads: '7.9M',
    icon: 'Braces',
  },
  {
    name: ' Citizens',
    description: 'Create custom NPCs with scripts, dialog, and scripted behaviors.',
    version: '2.0.33',
    author: 'CitizensDev',
    category: 'Fun',
    downloads: '5.3M',
    icon: 'Users',
  },
  {
    name: 'DiscordSRV',
    description: 'Link your Minecraft chat to a Discord channel and vice versa.',
    version: '1.27.0',
    author: 'Scarsz',
    category: 'Social',
    downloads: '3.2M',
    icon: 'MessageCircle',
  },
  {
    name: 'Multiverse-Core',
    description: 'Manage multiple worlds on a single server with separate inventories.',
    version: '4.3.12',
    author: 'Multiverse Team',
    category: 'World',
    downloads: '6.1M',
    icon: 'Globe',
  },
  {
    name: 'Geyser-Spigot',
    description: 'Allow Bedrock Edition players to join your Java Edition server.',
    version: '2.4.2',
    author: 'GeyserMC',
    category: 'Compatibility',
    downloads: '5.8M',
    icon: 'Bridge',
  },
  {
    name: 'ViaVersion',
    description: 'Let newer Minecraft clients connect to older server versions.',
    version: '5.2.1',
    author: 'ViaVersion',
    category: 'Compatibility',
    downloads: '4.9M',
    icon: 'ArrowLeftRight',
  },
];

/** Default server.properties seeded for every new server. */
export const DEFAULT_PROPERTIES: DefaultProperty[] = [
  { key: 'motd', value: 'A Minecraft Server', editable: true },
  { key: 'max-players', value: '20', editable: true },
  { key: 'server-port', value: '25565', editable: true },
  { key: 'gamemode', value: 'survival', editable: true },
  { key: 'difficulty', value: 'normal', editable: true },
  { key: 'pvp', value: 'true', editable: true },
  { key: 'online-mode', value: 'true', editable: true },
  { key: 'enable-command-block', value: 'false', editable: true },
  { key: 'spawn-protection', value: '16', editable: true },
  { key: 'view-distance', value: '10', editable: true },
  { key: 'simulation-distance', value: '10', editable: true },
  { key: 'allow-flight', value: 'false', editable: true },
  { key: 'white-list', value: 'false', editable: true },
  { key: 'enforce-whitelist', value: 'false', editable: true },
  { key: 'level-name', value: 'world', editable: false },
  { key: 'level-seed', value: '', editable: true },
  { key: 'level-type', value: 'minecraft\\:normal', editable: true },
  { key: 'generate-structures', value: 'true', editable: true },
  { key: 'max-world-size', value: '29999984', editable: true },
  { key: 'max-build-height', value: '256', editable: true },
  { key: 'enable-rcon', value: 'false', editable: true },
  { key: 'enable-query', value: 'false', editable: true },
  { key: 'resource-pack', value: '', editable: true },
  { key: 'force-gamemode', value: 'false', editable: true },
  { key: 'hardcore', value: 'false', editable: true },
];
